[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "studworks"
version = "0.2.0"
description = "StudWorks transforms images into accurate, editable LEGO models."
authors = [
    {name = "Mason Gensman"}
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "PySide6>=6.11",
    "numpy>=2.4",
    "PyOpenGL>=3.1",
    "PyGLM>=2.8",
]

[tool.setuptools.packages.find]
where = ["src"]